-- Baseline migration: single-tenant project (SIM Registration Portal)
-- Generated by /foundation:init equivalent — single-tenant variant.

-- Schemas
CREATE SCHEMA IF NOT EXISTS private;
CREATE SCHEMA IF NOT EXISTS audit;

-- Role enum — extended from baseline to include the SIM registration roles
CREATE TYPE public.app_role AS ENUM ('superadmin', 'admin', 'dealer', 'customer', 'auditor', 'user');

-- Profiles
CREATE TABLE public.profiles (
  id                UUID NOT NULL REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name         TEXT,
  avatar_url        TEXT,
  global_role       public.app_role NOT NULL DEFAULT 'customer',
  region_code       TEXT,           -- For dealers: their assigned region. For customers: their home region.
  created_at        TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at        TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Helper: updated_at trigger
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Helper: get user role
CREATE OR REPLACE FUNCTION private.get_user_role()
RETURNS TEXT
LANGUAGE SQL
SECURITY DEFINER
SET search_path = ''
STABLE
AS $$
  SELECT global_role::TEXT FROM public.profiles WHERE id = auth.uid()
$$;
GRANT EXECUTE ON FUNCTION private.get_user_role() TO authenticated;

-- Auto-create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (
    NEW.id,
    NEW.raw_user_meta_data ->> 'full_name',
    NEW.raw_user_meta_data ->> 'avatar_url'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = '';

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- RLS: profiles
CREATE POLICY "users_read_own" ON public.profiles
  FOR SELECT USING (id = auth.uid());
CREATE POLICY "users_update_own" ON public.profiles
  FOR UPDATE USING (id = auth.uid());

-- Triggers
CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Audit
CREATE TABLE audit.audit_logs (
  id              BIGSERIAL PRIMARY KEY,
  tenant_id       UUID,
  table_name      TEXT NOT NULL,
  record_id       UUID NOT NULL,
  operation       TEXT NOT NULL,
  old_data        JSONB,
  new_data        JSONB,
  changed_fields  JSONB,
  performed_by    UUID,
  performed_at    TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  ip_address      TEXT,
  user_agent      TEXT
);

CREATE INDEX idx_audit_table_name ON audit.audit_logs(table_name);
CREATE INDEX idx_audit_record_id ON audit.audit_logs(record_id);
CREATE INDEX idx_audit_performed_at ON audit.audit_logs(performed_at DESC);
CREATE INDEX idx_audit_performed_by ON audit.audit_logs(performed_by);

CREATE OR REPLACE FUNCTION audit.log_changes()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO audit.audit_logs (
    tenant_id, table_name, record_id, operation,
    old_data, new_data, changed_fields, performed_by
  ) VALUES (
    NULL,
    TG_TABLE_NAME,
    COALESCE(NEW.id, OLD.id),
    TG_OP,
    CASE WHEN TG_OP IN ('UPDATE', 'DELETE') THEN to_jsonb(OLD) ELSE NULL END,
    CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN to_jsonb(NEW) ELSE NULL END,
    CASE WHEN TG_OP = 'UPDATE' THEN (
      SELECT jsonb_object_agg(key, value)
      FROM jsonb_each(to_jsonb(NEW))
      WHERE to_jsonb(NEW) -> key IS DISTINCT FROM to_jsonb(OLD) -> key
    ) ELSE NULL END,
    auth.uid()
  );
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = '';

-- Audit triggers
CREATE TRIGGER audit_profiles AFTER INSERT OR UPDATE OR DELETE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION audit.log_changes();
